name: akshaya_flutter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  animated_read_more_text: ^0.0.6
  audioplayers: ^6.1.0
  auto_animated: ^3.2.0
  badges: ^3.1.2
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.6
  decimal: ^3.0.2
  device_info: ^2.0.0
  device_info_plus: ^10.1.2
  digital_signature_flutter: ^0.0.3
  dio: ^5.6.0
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.7
  file_picker: ^8.1.4
  fluent_ui: ^4.9.2
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_carousel_widget: ^3.1.0
  flutter_custom_month_picker: ^0.1.3
  flutter_local_notifications: ^18.0.1
  flutter_pdfview: ^1.3.2
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  flutter_timezone: ^3.0.1
  fluttertoast: ^8.2.8
  go_router: ^14.2.6
  http: ^1.2.2
  image: ^4.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  just_audio: ^0.9.40
  marquee: ^2.2.3
  multi_select_flutter: ^4.1.3
  open_filex: ^4.5.0
  package_info_plus: ^8.0.3
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pin_code_fields: ^8.0.1
  provider: ^6.1.2
  qr: ^3.0.0
  qr_flutter: ^4.1.0
  qrscan: ^0.3.3
  record: ^5.1.2
  share_plus: ^10.0.2
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  skeletonizer: ^1.4.2
  syncfusion_flutter_pdfviewer: ^27.1.58
  timezone: ^0.10.0
  toastification: ^2.3.0
  url_launcher: ^6.3.0
  vector_graphics: any
  webview_flutter: ^4.8.0
  youtube_player_flutter: ^8.0.0
#  decimal: ^2.2.0  # Check for the latest version on pub.dev
dependency_overrides:
  fading_edge_scrollview: ^4.1.1

dev_dependencies:
  build_runner: null
  flutter_gen_runner: null

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

#  dart run build_runner build
flutter_gen:
  output: lib/gen/
  line_length: 80
  package_parameter_enabled: true
  directory_path_enabled: true

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: hind
      fonts:
        - asset: assets/fonts/Hind-Light.ttf
          weight: 300
        - asset: assets/fonts/Hind-Regular.ttf
          weight: 400
        - asset: assets/fonts/Hind-Medium.ttf
          weight: 500
        - asset: assets/fonts/Hind-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Hind-Bold.ttf
          weight: 700
